/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#d9c2b2",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1f",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "surface-container-highest": "#e1e2e4",
        "secondary-container": "#51b5ff",
        "on-primary-fixed-variant": "#46464a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c7c6ca",
        "on-surface": "#191c1e",
        "secondary-fixed": "#cde5ff",
        "on-secondary-container": "#00456c",
        "on-error": "#ffffff",
        "secondary": "#006398",
        "secondary-fixed-dim": "#93ccff",
        "surface-container": "#edeef0",
        "on-background": "#191c1e",
        "primary": "#000000",
        "surface-container-low": "#f2f4f6",
        "background": "#f8f9fb",
        "surface-dim": "#d9dadc",
        "outline": "#76777b",
        "tertiary-container": "#25190f",
        "on-surface-variant": "#46464b",
        "on-tertiary": "#ffffff",
        "tertiary": "#000000",
        "surface": "#f8f9fb",
        "primary-fixed": "#e3e2e6",
        "surface-container-high": "#e7e8ea",
        "surface-variant": "#e1e2e4",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9fb",
        "on-secondary-fixed-variant": "#004b74",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#25190f",
        "inverse-primary": "#c7c6ca",
        "on-primary-container": "#848387",
        "on-tertiary-container": "#948072",
        "surface-tint": "#5e5e62",
        "on-primary-fixed": "#1b1b1f",
        "on-tertiary-fixed-variant": "#544437",
        "on-secondary-fixed": "#001d32",
        "error-container": "#ffdad6",
        "outline-variant": "#c7c6cb",
        "inverse-on-surface": "#f0f1f3",
        "tertiary-fixed": "#f7decd"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1.25rem",
        "margin": "2rem"
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "numeric-stat": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["26px", { lineHeight: "34px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeric-stat": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
